### ISSUE TITLE
按下 / 会导致网页卡死无响应

### ISSUE THREAD

**Issue by kulakilam** [gdh1995/vim-plus#457]
**Describe the bug**

按下 / 会导致网页卡死无响应

**To Reproduce**

打开一个网页，往下 /

**Browser, OS and Vimium C versions**

- Browser name: chrome
- Browser version: 版本 94.0.4606.81（正式版本） (x86_64)
- Vimium C version: 1.92.4
- OS name and version: macOS 11.4

**Comment by gdh1995** [comment]
这个功能是进入搜索模式，搜索词的输入框在右下角，你想操作网页的话，有三种办法：
按esc退出搜索模式、按f2把焦点切换到主体网页、用鼠标点一下网页内容或者空白区域来切换焦点



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月15日(周五) 晚上11:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 按下 / 会导致网页卡死无响应 (#457)




 
Describe the bug
 
按下 / 会导致网页卡死无响应
 
To Reproduce
 
Steps to reproduce the behavior:
 
打开一个网页，往下 /
 
Browser, OS and Vimium C versions
  
Browser name: chrome 

Browser version: 版本 94.0.4606.81（正式版本） (x86_64) 

Vimium C version: 1.92.4 

OS name and version: macOS 11.4 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kulakilam** [comment]
卡死是指键盘和鼠标操作都无响应，等待几秒钟后会出现上图的崩溃提示。

**Comment by gdh1995** [comment]
把其它扩展都临时禁用，然后刷新网页试试？改过`chrome://flags`下的设置吗？改过`/`绑定的快捷键吗？输入法是不是英文或者中文输入法，还是别的语言的？

**Comment by kulakilam** [comment]
找到原因了，安装的另外一个插件Katalon Recorder (Selenium tests generator)导致的。
按下 / 后，console会报下面的错误，点开chrome-extension链接显示是Katalon Recorder这个扩展程序报的。
DevTools failed to load source map: Could not load content for chrome-extension://ljdobmomdgdljniojadhoplhkpialdid/common/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

但是我把vimium c禁用后，倒不会有这个问题，可能是两个扩展程序有什么冲突吧。

**Comment by gdh1995** [comment]
这个要么不是真正的错误点，要么完全不算个错误。错误内容是`.js.map`文件找不到，但这个不影响扩展程序执行。

请问，禁掉这个扩展后，刷新一个普通网页，然后vimium c的`/`能在这个网页上正常用了吗？

**Comment by kulakilam** [comment]
禁用后可以正常使用vimium c了

**Comment by bushnerd** [comment]
同样遇到此问题。
