### ISSUE TITLE
Suggest adding specific comments of the issue when referencing them in the release page

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vim-plus#460]
When you would reference some of them in the future, I will have forgotten what I have proposed even as the author after a long time. It would be greatly appreciated that you direct to some single comment in a long issue, which is full of comments other than the decisive one.

**Comment by OnceThenEver** [comment]
It seems like v1.93.0's release note have been remodified to direct to comments. But I wonder why didn't the comment presented in the pop card:
![截屏2021-10-21 00 30 27](https://user-images.githubusercontent.com/66708845/138133601-a201ce3a-b068-4014-94de-982ebe9991ee.png)
It should be like this:
![截屏2021-10-21 00 20 46](https://user-images.githubusercontent.com/66708845/138132162-4938b463-564d-4469-8cd9-6639249f82c9.png)

**Comment by gdh1995** [comment]
Oh I see. I write MarkDown links like `[#325](https://github.com/gdh1995/vimium-c/issues/325#issuecomment-939656442)`, so that it will be rendered as a blue link of title="`#325`" and url="`a-comment-in-#325`" by GitHub, VS Code and other readers.

What you saw in `Playground`'s release page, I think, is because you write a link directly in release description, and GitHub recognizes such links and converts them to a much shorter version.

My text in https://github.com/gdh1995/vimium-c/releases are usually copied from https://github.com/gdh1995/vimium-c/blob/master/RELEASE-NOTES.md. Then, in order to keep `RELEASE-NOTES.md` look clean, and save my time when add a release, I don't want to directly insert a full URL there.

**Comment by OnceThenEver** [comment]
You're welcome. Directing to comments is already very helpful.
